### ISSUE TITLE
Add the "Wireframes" of the User Interface of your project.

### ISSUE THREAD

**Issue by dbc2201** [dbc2201/StepCounter#3]
- [x] Add all the images of all the activities (screens) visible in your project with proper labels.

**Comment by ashutosh-4** [comment]
Fixed issue #3, by adding Documentation/Wireframes that contains images of all screens visible in the project.

**Comment by dbc2201** [comment]
Please do not close the issues yourself, I will examine the task first and then will close the issues.

**Comment by dbc2201** [comment]
The wireframe images should have been written in a Wiki page, but all you have done is create a folder for it with the wrong naming convention.

**Comment by ashutosh-4** [comment]
I have created the wiki page containing the wireframes and also corrected the error in naming conventions.

**Comment by ashutosh-4** [comment]
wiki page-https://github.com/dbc2201/StepCounter/wiki/Wireframes
